### PR TITLE
add ClickHouse support

### PR DESCRIPTION
**Pull request by modelorona**
hey! I managed to get some code in to support ClickHouse. Never used it before but figured it was a good learning opportunity.

I've tested it with the sample db here: https://clickhouse.com/docs/en/getting-started/example-datasets/nyc-taxi and so far it's working fine.

You'll probably have more to test it with :)

### CODE REVIEW

**Comment by hkdeman** [comment]
This is great! Checking this out :)

**Comment by modelorona** [comment]
table is visible
image

data is visible
image

changing passenger count to 102
image

deleted first two rows
image

added row
image

**Comment by modelorona** [comment]
will check these merged changes locally

**Comment by modelorona** [comment]
worked fine on my machine :))

**Comment by hkdeman** [comment]
Looks good! Will merge this and see if I can add the chat functionality.

**Pull request merged**
